---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
schemes:
  - http
  
host: clusterconfig.104.131.17.220.xip.io
basePath: /DVP/API

paths:


  /{version}/CloudConfiguration/Cloud :
    
    post:
    
      parameters:
        - name: Create Cloud
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Cloud'
           
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
          
      responses:
       200:
        description: New Cloud has been created
        


  /{version}/CloudConfiguration/Cloud/{id}/Activate/{status} :
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: id
          
        - name: status
          in: path
          type: boolean
          description: status
          
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: Cloud configuration succeeded
  
        
  /{version}/CloudConfiguration/Cloud/{id} :
   
    get: 
      parameters: 
      
        - name: id
          in: path
          type: integer
          description: ID of the cloud
          required: true
          
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Cloud details returned
          
  /{version}/CloudConfiguration/Clouds :
   
    get: 
      parameters: 
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All Cloud details returned
          
  /{version}/CloudConfiguration/CallServer :
    
    post:
    
      parameters:
        - name: Create Cloud
          in: body
          description: Record
          schema:
           $ref: '#/definitions/CallServer'
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Cloud has been created


  /{version}/CloudConfiguration/CallServer/{id}/Activate/{status} :
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: id
          
        - name: status
          in: path
          type: boolean
          description: status
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: call server activation is succeeded
          
          
          
  /{version}/CloudConfiguration/CallServer/{id} :
   
    get: 
      parameters: 
      
        - name: id
          in: path
          type: integer
          description: ID of the call server
          required: true
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Call Server details returned
          
  
  /{version}/CloudConfiguration/CallServers :
   
    get: 
      parameters: 
      
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All Call Server details returned
          

  /{version}/CloudConfiguration/CallServer/{id}/AssignTo/{cloudid} :
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: id
          
        - name: cloudid
          in: path
          type: integer
          description: cloudid
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: call server assigning to cloud is succeeded
        
  /{version}/CloudConfiguration/Cloud/{childid}/SetParent/{parentid} :
    
    post:
    
      parameters:
        - name: childid
          in: path
          type: integer
          description: childid
          
        - name: parentid
          in: path
          type: integer
          description: parentid
          
        - name: version
          in: path
          type: string
          description: Version
          
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: Set call server to a parent server is completed
        
        
  /{version}/CloudConfiguration/LoadBalancer :
    
    post:
    
      parameters:
        - name: Create Load Balancer
          in: body
          description: Record
          schema:
           $ref: '#/definitions/LoadBalancer'
           
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Load Balancer has been created
        
  /{version}/CloudConfiguration/Network/TelcoNetwork :
    
    post:
    
      parameters:
        - name: Configure Telco NW
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Telco'
           
        - name: version
          in: path
          type: string
          description: Version
          
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Telco Newtwork has been configured
        
  /{version}/CloudConfiguration/Network/UserNetwork :
    
    post:
    
      parameters:
        - name: Configure EndUser NW
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Telco'
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Telco Newtwork has been configured     
    
  /{version}/CloudConfiguration/Network/{networkid}/SetTelcoNetworkToCloud/{cloudid} :
    
    post:
    
      parameters:
        - name: networkid
          in: path
          type: integer
          description: networkid
          
        - name: cloudid
          in: path
          type: integer
          description: cloudid
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: Set Telco Network to Cloud is done      
   
  /{version}/CloudConfiguration/Network/{networkid}/SetTelcoNetworkToUser/{userid}:
    
    post:
    
      parameters:
        - name: networkid
          in: path
          type: integer
          description: networkid
          
        - name: userid
          in: path
          type: integer
          description: userid
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: Set Telco Network to user is done 
        
        
     
     
  /{version}/CloudConfiguration/Networks :
   
    get: 
      parameters: 
      
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All Network details returned
          
          
  /{version}/CloudConfiguration/NetworksByClusterID/{id} :
   
    get: 
      parameters: 
      
        - name: version
          in: path
          type: string
          description: Version
          
        - name: id
          in: path
          type: integer
          description: ID of the call server
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All Network details returned
          
          
          
        
  /{version}/CloudConfiguration/CloudEndUser :
    
    post:
    
      parameters:
        - name: Add Cloud EndUser 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/CloudEndUser'
           
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Cloud end user has been inserted

  
        
  /{version}/CloudConfiguration/CloudEndUserByClusterID/{id} :
    
    get:
    
      parameters:
         
        - name: version
          in: path
          type: string
          description: Version
          
        - name: id
          in: path
          type: integer
          description: CloudId
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: All records of Cloud end user has been recieved



  /{version}/CloudConfiguration/Profile :
    
    post:
    
      parameters:
        - name: New Profile is added 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Profile'
           
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New profile has been inserted

  /{version}/CloudConfiguration/Profile/{profileid}/SetProfileToCallServer/{callserverid}:
    
    post:
    
      parameters:
        - name: profileid
          in: path
          type: integer
          description: profileid
          
        - name: callserverid
          in: path
          type: integer
          description: callserverid
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: Set Profile to callserver is done

  /{version}/CloudConfiguration/Profile/{profileid}/SetProfileToEndUser/{enduser}:
    
    post:
    
      parameters:
        - name: profileid
          in: path
          type: integer
          description: profileid
          
        - name: enduser
          in: path
          type: integer
          description: enduser
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: Set Profile to Enduser is done


  /{version}/CloudConfiguration/Profile/{id} :
   
    get: 
      parameters: 
      
        - name: id
          in: path
          type: integer
          description: ID of the Profile
          required: true
        
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Profile details returned 

  /{version}/CloudConfiguration/Profiles :
   
    get: 
      parameters: 
      
        - name: version
          in: path
          type: string
          description: Version
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
        
      responses:
        200:
          description: All Profile details returned 

  /{version}/CloudConfiguration/IPAddress :
    
    post:
    
      parameters:
        - name: Configure IP 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/IP'
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
        - name: version
          in: path
          type: string
          description: Version
          
      responses:
       200:
        description: New profile has been inserted




definitions:        
  Cloud:
    properties:
     
     CloudModel:
      type: integer
     Name: 
      type: string
     Class:
      type: string
     Type: 
      type: string
     Category:
      type: string
     TenantId:
      type: integer
     CompanyId:
      type: integer
      
      
  CallServer:
    properties:
     
     Activate:
      type: boolean
     Name: 
      type: string
     Class:
      type: string
     Type: 
      type: string
     Category:
      type: string
     TenantId:
      type: integer
     CompanyId:
      type: integer
     Code:
      type: integer
     InternalIP:
      type: string
      
  LoadBalancer:
    properties:
     
     Type: 
      type: string
     MainIP:
      type: string
     ClusterId:
      type: integer
      
  Telco:
    properties:
     
     Network:
      type: string
      description: "ex:- 192.168.1.0"
      
     Mask: 
      type: integer
      description: " 32,24 etc (Network prefix notation)"
     NATIP:
      type: string
     TenantId:
      type: integer
     CompanyId:
      type: integer
      
  CloudEndUser:
    properties:
     
    
     SIPConnectivityProvision: 
      type: integer
     Domain:
      type: string
     TenantId:
      type: integer
     CompanyId:
      type: integer
     ClusterID:
      type: integer
      
  Profile:
    properties:
     
     ProfileName:
      type: string
     MainIp: 
      type: string
     InternalIp:
      type: string
     InternalRtpIp:
      type: string
     ExternalIp:
      type: string
     ExternalRtpIp:
      type: string
     Port :
      type: integer
     ObjClass:
      type: string
     ObjType: 
      type: string
     ObjCategory:
      type: string
     TenantId:
      type: integer
     CompanyId:
      type: integer
      
      
  IP:
    properties:
     
     CallserverID:
      type: integer
     MainIp: 
      type: string
     IP:
      type: string
     IsAllocated:
      type: boolean  
      
      