swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: >
    #### Echos back every URL, method, parameter and header

    Feel free to make a path or an operation and use **Try Operation** to test
    it. The echo server will

    render back everything.
schemes:
  - http
host: conference.104.131.67.21.xip.io
basePath: /DVP/API
paths:

  '/{version}/ConferenceConfiguration/ConferenceRoom':
    post:
      parameters:
        - name: New Context Record
          in: body
          description: Record
          schema:
            $ref: '#/definitions/Conference'
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: New Conference Room Added
  
  '/{version}/ConferenceConfiguration/ConferenceRoom/{ConfName}':
    put:
      parameters:
        - name: Conference Room Details
          in: body
          description: Update
          schema:
            $ref: '#/definitions/UpdtConference'
            
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: ConfName
          in: path
          type: string
          description: Conference Room Name
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Conference updated
    get:
      parameters:
        - name: ConfName
          in: path
          type: string
          description: Conference name
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Get Conference User details succeeded
    delete:
      parameters:
        - name: ConfName
          in: path
          type: string
          description: Conference name
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Conference Room Deleted succeeded
  
  '/{version}/ConferenceConfiguration/ConferenceRoom/{ConfName}/Time':
    post:
      parameters:
        - name: Conference Room Times
          in: body
          description: Update
          schema:
            $ref: '#/definitions/UpdtConfTime'
            
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - name: ConfName
          in: path
          type: string
          description: Conference name
          required: true
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: New Mapping happens
          
  '/{version}//ConferenceConfiguration/ConferenceRoom/{CfName}/AssignCloudEndUser/{CloudUserId}':
    post:
      parameters:
        - name: CfName
          in: path
          type: string
          description: Conference name
          required: true
          
        - name: CloudUserId
          in: path
          type: string
          description: CloudUser Id
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: Cloud end user assigned to Conference successfully
  
  '/{version}/ConferenceConfiguration/ConferenceUser':
    post:
      parameters:
        - name: Conference Room Times
          in: body
          description: Update
          schema:
            $ref: '#/definitions/User'
            
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: New Conference user added
  
  '/{version}/ConferenceConfiguration/ConferenceUser/{UserId}/AssignToRoom/{RoomName}':
    post:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: UserId
          in: path
          type: string
          description: Id of Conference user
          required: true
          
        - name: RoomName
          in: path
          type: integer
          description: ConferenceRoom Name
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Conference user added to conference successfully
    
  '/{version}/ConferenceConfiguration/ConferenceUser/{UserId}/AddToRoom/{RoomName}':
    post:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: UserId
          in: path
          type: string
          description: Id of Conference user
          required: true
          
        - name: RoomName
          in: path
          type: integer
          description: ConferenceRoom Name
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Sipuser in Conference user list added to conference successfully        
  
  '/{version}/ConferenceConfiguration/ConferenceUser/{UserId}/Mode':
    post:
      parameters:
        - name: UserId
          in: path
          type: string
          description: UserID
          required: true
          
        - name: Add Sip User group
          in: body
          description: Record
          schema:
            $ref: '#/definitions/Modes'
            
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
      responses:
        '200':
          description: User modes updated
  
  '/{version}/ConferenceConfiguration/ConferenceUser/{UserId}':
    delete:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          
          type: string
        - name: UserId
          in: path
          type: integer
          description: Conference UserID
          required: true
          
      responses:
        '200':
          description: Conference user Deleted
    get:
      parameters:
        - name: UserId
          in: path
          type: integer
          description: Name of Group
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Conference user record recieved
  
  
          
  '/{version}/ConferenceConfiguration/ConferenceRooms':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: Get Conference Rooms
          
  '/{version}/ConferenceOperations/ConferenceUser/{User}/Mute':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: User
          in: path
          type: string
          description: Name of User
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: User mute mode on
         
  '/{version}/ConferenceOperations/ConferenceUser/{User}/UnMute':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: User
          in: path
          type: string
          description: Name of User
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: User mute mode off
  
  '/{version}/ConferenceOperations/ConferenceUser/{User}/Deaf':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: User
          in: path
          type: string
          description: Name of user
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: User Deaf mode on
  
  '/{version}/ConferenceOperations/ConferenceUser/{User}/UnDeaf':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: User
          in: path
          type: string
          description: Name of User
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: User Deaf mode off
  
  '/{version}/ConferenceOperations/ConferenceUser/{User}/Kick':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: User
          in: path
          type: string
          description: Name of User
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: User kicked from conference
  
  '/{version}/ConferenceOperations/Conference/{ConfName}/Users/Mute':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: ConfName
          in: path
          type: string
          description: Name of Conference
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: All users of conference Muted
          
  '/{version}/ConferenceOperations/Conference/{ConfName}/Users/UnMute':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: ConfName
          in: path
          type: string
          description: Name of Conference
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: All users of conference Unmuted
  '/{version}/ConferenceOperations/Conference/{ConfName}/Users/Deaf':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: ConfName
          in: path
          type: string
          description: Name of Conference
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: All users of conference Deafed
  '/{version}/ConferenceOperations/Conference/{ConfName}/Users/UnDeaf':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: ConfName
          in: path
          type: string
          description: Name of Conference
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: All users of conference UnDeafed
  '/{version}/ConferenceOperations/Conference/{ConfName}/Lock':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: ConfName
          in: path
          type: string
          description: Name of Conference
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Conference Locked
  '/{version}/ConferenceOperations/Conference/{ConfName}/Unlock':
    get:
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: ConfName
          in: path
          type: string
          description: Name of Conference
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
      responses:
        '200':
          description: Conference UnLocked
          
  '/{version}/Conference/{confName}/user':
    
    post:
      parameters:
        - name: confName
          in: path
          type: string
          description: Name of Conference
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
          
        - name: ConfUser data
          in: body
          description: Record
          schema:
            $ref: '#/definitions/UpdtUser'
          
      responses:
        '200':
          description: Conference user added
                  
          
  '/{version}/ConferenceUser/{UserId}':
    
    put:
      parameters:
        - name: UserId
          in: path
          type: string
          description: UserId of ConferenceUser
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
        - name: ConfUser data
          in: body
          description: Record
          schema:
            $ref: '#/definitions/UpdtUser'
          
      responses:
        '200':
          description: Conference user Updated   
          
          
  '/{version}/Conference/{confName}/users':
    
    get:
      parameters:
        - name: confName
          in: path
          type: string
          description: confName of Conference
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ''
          required: true
          type: string
        
          
      responses:
        '200':
          description: Conference users recieved 
          
          
          
definitions:
  Conference:
    properties:
      Extension:
        type: string
      ConferenceName:
        type: string
      Description:
        type: string
      AllowAnonymousUser:
        type: boolean
      StartTime:
        type: string
      EndTime:
        type: string
      Domain:
        type: string
      IsLocked:
        type: boolean
      MaxUser:
        type: string
      Pin:
        type: string
        
  UpdtConference:
    properties:
      
      AllowAnonymousUser:
        type: boolean
      StartTime:
        type: string
      EndTime:
        type: string
      Domain:
        type: string
      IsLocked:
        type: boolean
      MaxUser:
        type: string
      Pin:
        type: string
  
  UpdtConfTime:
    properties:
      
      
      StartTime:
        type: string
      EndTime:
        type: string
      
  
  
  User:
    properties:
      SipUserUuid:
        type: string
      ActiveTalker:
        type: boolean
      Def:
        type: boolean
      Mute:
        type: boolean
      Mod:
        type: boolean
      ObjCategory:
        description: User catagory
        type: string
        enum:
          - EXTERNAL
          - INRENAL
      CurrentDef:
        type: boolean
      CurrentMute:
        type: boolean
      CurrentMod:
        type: boolean
      Destination:
        type: string
      JoinType:
        description: Join Types
        type: string
        enum:
          - IN
          - OUT
      
  Modes:
    properties:
      Def:
        type: boolean
      Mute:
        type: boolean
      Mod:
        type: boolean
        
        
  UpdtUser:
    properties:
      SipUserUuid:
        type: string
      ActiveTalker:
        type: boolean
      Def:
        type: boolean
      Mute:
        type: boolean
      Mod:
        type: boolean
      ObjCategory:
        description: User catagory
        type: string
        enum:
          - EXTERNAL
          - INRENAL
      CurrentDef:
        type: boolean
      CurrentMute:
        type: boolean
      CurrentMod:
        type: boolean
      Destination:
        type: string
      JoinType:
        description: Join Types
        type: string
        enum:
          - IN
          - OUT
      UserStatus:
        type: boolean
