---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
schemes:
  - http

basePath: /DVP/API
paths:

  /{hostVersion}/PBXService/PBXUser/{PbxUserUuid}/AllowedNumbers:
    
    post:
    
      parameters:
      
        - name: PbxUserUuid
          in: path
          type: string
          description: PbxUserUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        - in: body
          name: AllowedNumbers
          description: Allowed Numbers
          required: true
          schema: {
            type: array,
            items: {
               type: string
                   }
                }
          
      responses:
       200:
        description: Allowed numbers added
        
  /{hostVersion}/PBXService/PBXUser/{PbxUserUuid}/DayPersonalGreeting/{FileUuid}:
    
    post:
    
      parameters:
      
        - name: PbxUserUuid
          in: path
          type: string
          description: PbxUserUuid
          
        - name: FileUuid
          in: path
          type: string
          description: FileUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: DayPersonalGreeting added
        
  /{hostVersion}/PBXService/PBXUser/{PbxUserUuid}/NightPersonalGreeting/{FileUuid}:
    
    post:
    
      parameters:
      
        - name: PbxUserUuid
          in: path
          type: string
          description: PbxUserUuid
          
        - name: FileUuid
          in: path
          type: string
          description: FileUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: NightPersonalGreeting added
        
  /{hostVersion}/PBXService/PBXUser/{PbxUserUuid}/PersonalGreetingStatus/{EnableStatus}:
    
    post:
    
      parameters:
      
        - name: PbxUserUuid
          in: path
          type: string
          description: PbxUserUuid
          
        - name: EnableStatus
          in: path
          type: boolean
          description: EnableStatus
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: PersonalGreetingStatus updated
        
  /{hostVersion}/PBXService/PBXUser/{PbxUserUuid}/AllowedNumber/{AllowedNumber}/UnAssign:
    
    post:
    
      parameters:
      
        - name: PbxUserUuid
          in: path
          type: string
          description: PbxUserUuid
          
        - name: AllowedNumber
          in: path
          type: string
          description: AllowedNumber
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Allowed number unassigned
        
  /{hostVersion}/PBXService/FeatureCodeTemplate:
    
    post:
    
      parameters:
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        - name: Feature Code Details
          in: body
          description: FC Details
          schema:
           $ref: '#/definitions/FeatureCode'
          
      responses:
       200:
        description: Feature Code Template Added
        
        
  /{hostVersion}/PBXService/PBXUser/{userUuid}/FollowMe:
    
    post:
    
      parameters:
      
        - name: userUuid
          in: path
          type: string
          description: userUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        - name: Feature Code Details
          in: body
          description: FC Details
          schema:
           $ref: '#/definitions/FollowMe'
          
      responses:
       200:
        description: FollowMe Added
        
        
  /{hostVersion}/PBXService/PBXUser/{userUuid}/Forwarding:
    
    post:
    
      parameters:
      
        - name: userUuid
          in: path
          type: string
          description: userUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        - name: Feature Code Details
          in: body
          description: FC Details
          schema:
           $ref: '#/definitions/Forwarding'
          
      responses:
       200:
        description: Forwarding Added
        
        
  /{hostVersion}/PBXService/FollowMe/{fmId} :
  
  
    get:
      parameters:
      
        - name: fmId
          in: path
          type: string
          description: follow me id
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Follow me configurations returned 
    
    delete:
      
    
      parameters:
        - name: fmId
          in: path
          type: integer
          description: fmId
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        
          
      responses:
       200:
        description: Follow Me config has been deleted
        
        
  /{hostVersion}/PBXService/Forwarding/{fwdId} :
    
    delete:
      
    
      parameters:
        - name: fwdId
          in: path
          type: integer
          description: fwdId
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        
          
      responses:
       200:
        description: Forwarding config has been deleted
        
    get:
      parameters:
      
        - name: fwdId
          in: path
          type: string
          description: forwarding id
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Forwarding configurations returned
          
  
  /{hostVersion}/PBXService/PBXUser:
    
    post:
    
      parameters:
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        - name: PbxUser
          in: body
          description: PbxUser Details
          schema:
           $ref: '#/definitions/PbxUser'
          
      responses:
       200:
        description: Pbx User Added
        
  /{hostVersion}/PBXService/PbxUserTemplate:
    
    post:
    
      parameters:
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        - name: PbxUserTemplate
          in: body
          description: PbxUserTemplate Details
          schema:
           $ref: '#/definitions/PbxUserTemplate'
          
      responses:
       200:
        description: PbxUserTemplate Added  
        
        
  /{hostVersion}/PBXService/PBXUser/{pbxUser}/SetPbxUserTemplate/{templateId}:
    
    post:
    
      parameters:
      
        - name: pbxUser
          in: path
          type: string
          description: pbxUser
          
        - name: templateId
          in: path
          type: integer
          description: templateId
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: PbxUserTemplate Assigned
        
  /{hostVersion}/PBXService/PBXUser/{PbxUserUuid}/PbxUserTemplate/UnAssign:
    
    post:
    
      parameters:
      
        - name: PbxUserUuid
          in: path
          type: string
          description: PbxUserUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: PbxUserTemplate Un Assigned 
        
        
  /{hostVersion}/PBXService/PbxUserTemplate/{templateId} :
    
    delete:
    
      parameters:
        - name: templateId
          in: path
          type: string
          description: templateId
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
          
      responses:
       200:
        description: Pbx user template has been deleted
        
    get:
      parameters:
      
        - name: templateId
          in: path
          type: string
          description: pbx template id
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Pbx user template returned
          
  
  /{hostVersion}/PBXService/PBXUser/{PbxUserUuid}:
   
   get:
      parameters:
      
        - name: PbxUserUuid
          in: path
          type: string
          description: PbxUserUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Pbx User returned 
          
   delete:
    
      parameters:
        - name: PbxUserUuid
          in: path
          type: string
          description: pbxUserUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        
          
      responses:
       200:
        description: Pbx user has been deleted
        
        
  /{hostVersion}/PBXService/FeatureCodes:
   
   get:
      parameters:
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Feature codes returned
          

  /{hostVersion}/PBXService/PBXUsers:
   
   get:
      parameters:
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Pbx users returned
          
          
  /{hostVersion}/PBXService/PbxUserTemplates:
   
   get:
      parameters:
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: PbxUserTemplates returned
          
  /{hostVersion}/PBXService/PBXUser/{userUuid}/FollowMe:
   
   get:
      parameters:
        
        - name: userUuid
          in: path
          type: string
          description: pbxUserUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Follow Me config for user returned
          
          
  /{hostVersion}/PBXService/PBXUser/{userUuid}/Forwarding:
   
   get:
      parameters:
        
        - name: userUuid
          in: path
          type: string
          description: pbxUserUuid
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Forwarding config for user returned
          
  /{hostVersion}/PBXService/PbxMasterData:
    
    post:
    
      parameters:
      
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        - name: PbxMasterData
          in: body
          description: PbxMasterData Details
          schema:
           $ref: '#/definitions/PbxMasterData'
          
      responses:
       200:
        description: Pbx Master Data Added
        
        
  /{hostVersion}/PBXService/PbxMasterData/{id}:
   
   get:
      parameters:
        
        - name: id
          in: path
          type: integer
          description: id
          
        - name: hostVersion
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Pbx master data returned      
          
     
definitions:

  PbxUserTemplate:
    properties:
     
     CallDivertUser:
      type: string
     CallDivertNumber: 
      type: string
     ObjCategory:
      type: string
      
  PbxMasterData:
    properties:
     
     BypassMedia:
      type: boolean
     IgnoreEarlyMedia: 
      type: boolean
     VoicemailEnabled:
      type: boolean
     
  
  PbxUser:
    properties:
     
     UserUuid:
      type: string
     BypassMedia: 
      type: boolean
     IgnoreEarlyMedia:
      type: boolean
     VoicemailEnabled:
      type: boolean
     ScheduleId:
      type: integer
     AllowOutbound:
      type: boolean
     AdvancedRouteMethod :
      type: string
     FollowMeMechanism:
      type: string
     Pin:
      type: string
  

      
  FeatureCode:
    properties:
     
     PickUp:
      type: integer
     Intercept:
      type: integer
     Park:
      type: integer
     Voicemail:
      type: integer
     Barge:
      type: integer
      
  FollowMe:
    properties:
     
     DestinationNumber:
      type: string
     RingTimeout:
      type: integer
     Priority:
      type: integer
     ObjCategory:
      type: string
      
  Forwarding:
    properties:
     
     DestinationNumber:
      type: string
     RingTimeout:
      type: integer
     DisconnectReason:
      type: integer
     ObjCategory:
      type: string
     IsActive:
      type: boolean
  
  
    
     
 
 
