---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.

schemes:
  - http

basePath: /DVP/API
paths:
  /{version}/LimitAPI/Schedule/Appointment:
    
    post:
      
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: New Appointment Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Appointment'
           
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Appointment Record Added
        
  /{version}/LimitAPI/Schedule:
  
    post:
      
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: New Schedule Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Schedule'
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Schedule Record Added
        
  /{version}/LimitAPI/Schedule/{id}:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: id
          in: path
          type: integer
          description: SceduleID
          required: true
          
        - name: Update Schedule details
          in: body
          description: Update
          schema:
           $ref: '#/definitions/UpdtSchedule'
           
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Mapping happens
        
  /{version}/LimitAPI/Schedule/{sid}/AddAppointment/{appid}:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: sid
          in: path
          type: integer
          description: ScheduleId
          required: true
        
        - name: appid
          in: path
          type: integer
          description: AppointmentID
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Mapping happens
        
  /{version}/LimitAPI/Schedule/Appointment/{id}:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: id
          in: path
          type: integer
          description: AppointmentID
          required: true
          
        - name: Availability updation 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/UpdtApp'
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Updation succeeded
        
  /{version}/LimitAPI/Limit:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: Limit record 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/LimitInfo'
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Limit record insertion Succeeded
        
  /{version}/LimitAPI/Limit/Max/{lid}:
  
    post:
      
      parameters:
        - name: Update Max 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/LimMax'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: lid
          in: path
          type: integer
          description: LimitId
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Limit max updation Succeeded
        
  /{version}/LimitAPI/Limit/{lid}/Activate/{status}:
  
    post:
      
      parameters:
        
        - name: version
          in: path
          type: integer
          description: Version checking
          required: true
          
        - name: lid
          in: path
          type: string
          description: LimitId
          required: true
          
        - name: status
          in: path
          type: string
          description: LimitId
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Limit max updation Succeeded
  
 
        
  /{version}/LimitAPI/Schedule/Increment/{key}:
   
   get:
      parameters:
        - name: key
          in: path
          type: string
          description: ID of Limit
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        
      responses:
        200:
          description: Incrementation happened
          
          
  /{version}/LimitAPI/Schedule/Decrement/{key}:
   
   get:
      parameters:
        - name: key
          in: path
          type: string
          description: ID of Limit
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
        
      responses:
        200:
          description: Decrementation happened
          
  /{version}/LimitAPI/Schedule/ValidAppointment/{scheduleID}:
   
   get:
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - name: scheduleID
          in: path
          type: string
          description: Schedule Id of Appointment
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
        200:
          description: Decrementation happened
   
  /{version}/LimitAPI/Schedule/{id}/ValidAppointment/{date}/{time}:
   
   get:
      parameters:
      
        - name: id
          in: path
          type: string
          description: date checking
          required: true
        
        - name: date
          in: path
          type: string
          description: date checking
          required: true
          
        - name: time
          in: path
          type: string
          description: time checking
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Decrementation happened       
   
        
  /{version}/LimitHandler/ScheduleApi/ApplicationThroughSchedule/{dt}/{tm}:
   
   get:
      parameters:
        - name: dt
          in: path
          type: string
          description: date checking
          required: true
        
          
        - name: tm
          in: path
          type: string
          description: time checking
          required: true
          
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
        200:
          description: Decrementation happened       
        
  /{version}/LimitAPI/Schedule/{id}:
   
   get:
      parameters:
        - name: id
          in: path
          type: integer
          description: ID of the schedule
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Schedule picked
          
  /{version}/LimitAPI/Schedule/{id}/Action:
   
   get:
      parameters:
        - name: id
          in: path
          type: integer
          description: ID of the schedule
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Schedule Action picked   
          
  /{version}/LimitAPI/Schedule/{id}/Appointment:
   
   get:
      parameters:
        - name: id
          in: path
          type: integer
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Appointment picked 
          
  /{version}/LimitAPI/Schedule/Appointmen/{id}/Action:
   
   get:
      parameters:
        - name: id
          in: path
          type: integer
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Appointment Action picked 
          
  /{version}/LimitAPI/Limit/Current/{Rid}:
   
   get:
      parameters:
        - name: Rid
          in: path
          type: string
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Appointment Action picked 
  
  /{version}/LimitAPI/Limit/MaxLimit/{Rid}:
   
   get:
      parameters:
        - name: Rid
          in: path
          type: string
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Appointment Action picked 
          
definitions:
  Appointment:
    properties:
     ScheduleId:
      type: integer
     AppointmentName:
      type: string
     Action:
      type: string
     ExtraData:
      type: string
     StartDate:
      type: string
     EndDate:
      type: string
     StartTime:
      type: string
     EndTime:
      type: string
     DaysOfWeek:
      type: string
     
      
      
  Schedule:
    properties:
     
     ScheduleName:
      type: string
     Action:
      type: string
     ExtraData:
      type: string
     
  UpdtApp:
    properties:

     Action:
      type: string
     ExtraData:
      type: string
     StartDate:
      type: string
     EndDate:
      type: string
     StartTime:
      type: string
     EndTime:
      type: string
     DaysOfWeek:
      type: string
     
  
  
  
      
  LimitInfo:
    properties:
    
     LimitDescription:
      type: string
     MaxCount:
      type: integer
     Enable:
      type: boolean
      
  LimMax:
    properties:
     
     MaxCount:
      type: integer
     
    
  
     
 
 