---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
host: 127.0.0.1:8011
schemes:
  - http

basePath: /DVP/API
paths:
  /{version}/LimitHandler/Schedule/Appointment:
    
    post:
      
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: New Appointment Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Appointment'
      responses:
       200:
        description: New Appointment Record Added
        
  /{version}/LimitHandler/Schedule/Schedule:
  
    post:
      
      parameters:
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: New Schedule Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Schedule'
      responses:
       200:
        description: New Schedule Record Added
        
  /{version}/LimitHandler/Schedule/UpdateSchedule/{id}:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: id
          in: path
          type: string
          description: SceduleID
          required: true
          
        - name: Update Schedule details
          in: body
          description: Update
          schema:
           $ref: '#/definitions/UpdtSchedule'
      responses:
       200:
        description: New Mapping happens
        
  /{version}/LimitHandler/Schedule/ScheduleId/{SID}/ToAppointment/{AID}:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: SID
          in: path
          type: string
          description: ScheduleId
          required: true
        
        - name: AID
          in: path
          type: string
          description: AppointmentID
          required: true
      responses:
       200:
        description: New Mapping happens
        
  /{version}/LimitHandler/Schedule/Appointment/{id}:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: id
          in: path
          type: string
          description: AppointmentID
          required: true
          
        - name: Availability updation 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/UpdtApp'
      responses:
       200:
        description: Updation succeeded
        
  /{version}/LimitHandler/limitapi/LimitRecord:
  
    post:
      
      parameters:
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: Limit record 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/LimitInfo'
      responses:
       200:
        description: Limit record insertion Succeeded
        
  /{version}/LimitHandler/LimitApi/LimitMax/{LID}:
  
    post:
      
      parameters:
        - name: Update Max 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/LimMax'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: LID
          in: path
          type: string
          description: LimitId
          required: true
      responses:
       200:
        description: Limit max updation Succeeded
        
  /{version}/LimitHandler/LimitApi/EnableState/{LID}:
  
    post:
      
      parameters:
        - name: Update Enability 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/LimEnbl'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: LID
          in: path
          type: string
          description: LimitId
          required: true
          
      responses:
       200:
        description: Limit max updation Succeeded
  
 
        
  /{version}/LimitHandler/LimitApi/LimitIncrement/{key}:
   
   get:
      parameters:
        - name: key
          in: path
          type: string
          description: ID of Limit
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        
      responses:
        200:
          description: Incrementation happened
          
          
  /{version}/LimitHandler/LimitApi/LimitDecrement/{key}:
   
   get:
      parameters:
        - name: key
          in: path
          type: string
          description: ID of Limit
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        
      responses:
        200:
          description: Decrementation happened
          
  /{version}/LimitHandler/Schedule/ValidAppointment:
   
   get:
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
      responses:
        200:
          description: Decrementation happened
   
  /{version}/LimitHandler/Schedule/CheckAvailablesFor/{dt}/{dy}/{tm}:
   
   get:
      parameters:
        - name: dt
          in: path
          type: string
          description: date checking
          required: true
        
        - name: dy
          in: path
          type: string
          description: day checking
          required: true
          
        - name: tm
          in: path
          type: string
          description: time checking
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Decrementation happened       
   
        
  /{version}/LimitHandler/Schedule/ApplicationThroughSchedule/{cmp}/{tent}/{dt}/{dy}/{tm}:
   
   get:
      parameters:
        - name: dt
          in: path
          type: string
          description: date checking
          required: true
        
        - name: dy
          in: path
          type: string
          description: day checking
          required: true
          
        - name: tm
          in: path
          type: string
          description: time checking
          required: true
          
        - name: cmp
          in: path
          type: integer
          description: company checking
          required: true
          
        - name: tent
          in: path
          type: integer
          description: company checking
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Decrementation happened       
        
  /{version}/LimitHandler/Schedule/Schedule/{id}:
   
   get:
      parameters:
        - name: id
          in: path
          type: string
          description: ID of the schedule
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Schedule picked
          
  /{version}/LimitHandler/Schedule/ScheduleAction/{id}:
   
   get:
      parameters:
        - name: id
          in: path
          type: string
          description: ID of the schedule
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Schedule Action picked   
          
  /{version}/LimitHandler/Schedule/Appointment/{id}:
   
   get:
      parameters:
        - name: id
          in: path
          type: string
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Appointment picked 
          
  /{version}/LimitHandler/Schedule/AppointmentAction/{id}:
   
   get:
      parameters:
        - name: id
          in: path
          type: string
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Appointment Action picked 
          
  /{version}/LimitHandler/LimitApi/CurrentLimit/{Rid}:
   
   get:
      parameters:
        - name: Rid
          in: path
          type: string
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Appointment Action picked 
  
  /{version}/LimitHandler/LimitApi/MaxLimit/{Rid}:
   
   get:
      parameters:
        - name: Rid
          in: path
          type: string
          description: ID of the Appointment
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
      responses:
        200:
          description: Appointment Action picked 
          
definitions:
  Appointment:
    properties:
     ScheduleId:
      type: integer
     AppointmentName:
      type: string
     Action:
      type: string
     ExtraData:
      type: string
     StartDate:
      type: string
     EndDate:
      type: string
     StartTime:
      type: string
     EndTime:
      type: string
     DaysOfWeek:
      type: string
     
      
      
  Schedule:
    properties:
     
     ScheduleName:
      type: string
     Action:
      type: string
     ExtraData:
      type: string
     
     
      

      
  UpdtSchedule:
    properties:
     
     Action: 
      type: string
     ExtraData:
      type: string
     
     
  
  UpdtApp:
    properties:

     Action:
      type: string
     ExtraData:
      type: string
     StartDate:
      type: string
     EndDate:
      type: string
     StartTime:
      type: string
     EndTime:
      type: string
     DaysOfWeek:
      type: string
     
  
  
  
      
  LimitInfo:
    properties:
    
     LimitDescription:
      type: string
     MaxCount:
      type: integer
     Enable:
      type: boolean
      
  LimMax:
    properties:
     
     MaxCount:
      type: integer
     
    
      
  LimEnbl:
    properties:
     
     Enable:
      type: boolean
     LimitId:
      type: string
    
     
 
 