swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: >
    #### Echos back every URL, method, parameter and header

    Feel free to make a path or an operation and use **Try Operation** to test
    it. The echo server will

    render back everything.
schemes:
  - http
host: voxboneapi.104.131.67.21.xip.io
basePath: /DVP/API
paths:
  '/{version}/voxbone/trunk/trunksetup':
    post:
      parameters:
        - name: New Campaign Record
          in: body
          description: Record
          schema:
            $ref: '#/definitions/TrunkSetup'
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - in: header
          name: Authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: trunk setup succeeded
          
  '/{version}/voxbone/trunk/{trunkid}/limitnumber':
    post:
      parameters:
        - name: Set limit to number
          in: body
          description: Record
          schema:
            $ref: '#/definitions/TrunkNumber'
        - name: trunkid
          in: path
          type: integer
          description: ID of trunk
          required: true
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - in: header
          name: Authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: Limit allocated to number
          
    
  '/{version}/voxbone/inventory/listcountries/{pageNumber}/{pageSize}':
    get:
      parameters:
        - name: pageNumber
          in: path
          type: integer
          description: page number
          required: true
        
        - name: pageSize
          in: path
          type: integer
          description: Page size
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: Authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: Countries recieved
          
  '/{version}/voxbone/inventory/listdidgroup/{countryCodeA3}/{pageNumber}/{pageSize}':
    get:
      parameters:
        - name: pageNumber
          in: path
          type: integer
          description: page number
          required: true
        
        - name: pageSize
          in: path
          type: integer
          description: Page size
          required: true
        
        - name: countryCodeA3
          in: path
          type: string
          description: countryCodeA3
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: Authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: dids recieved
          
          
  '/{version}/voxbone/inventory/listdidgroup/type/{didType}/{countryCodeA3}/{pageNumber}/{pageSize}':
    get:
      parameters:
        - name: didType
          in: path
          type: string
          description: did type
          required: true
          
        - name: pageNumber
          in: path
          type: integer
          description: page number
          required: true
        
        - name: pageSize
          in: path
          type: integer
          description: Page size
          required: true
        
        - name: countryCodeA3
          in: path
          type: string
          description: countryCodeA3
          required: true
        
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - in: header
          name: Authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: Dids recieved
          
          
  '/{version}/voxbone/order/OrderDids':
    post:
      parameters:
        
        - name: order Dids
          in: body
          description: Record
          schema:
            $ref: '#/definitions/OrderDids'
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - in: header
          name: Authorization
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: New Campaign Added
    
   

  
          
          
  
      
definitions:


  TrunkSetup:
    properties:
      FaxType:
        type: string
      IpUrl:
        type: string
      TrunkCode:
        type: string
      TrunkName:
        type: string
      LbId:
        type: integer
      OperatorCode:
        type: string
      OperatorName:
        type: string
  
  TrunkNumber:
    properties:
      limitDescription:
        type: string
      maxCount:
        type: integer
      phoneNumber:
        type: string
      
      

  OrderDids:
    properties:
      customerReference:
        type: string
      description:
        type: string
      didGroupId:
        type: integer
      quantity:
        type: integer
      countryCodeA3:
        type: string
      
  