---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
schemes:
  - http
  

basePath: /DVP/API
paths:
  /{version}/SipUser/Context:
    
    post:
    
      parameters:
        - name: New Context Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Context'
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
      responses:
       200:
        description: New Context Record Added
          
        
        
  /{version}/SipUser/User:
  
    post:
      
      parameters:
        - name: New UAC Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/UAC'
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Schedule Record Added
        
  /{version}/SipUser/User/{Username}:
  
    post:
      
      parameters:
        - name: Update Schedule details
          in: body
          description: Update
          schema:
           $ref: '#/definitions/UpdtUAC'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: Username
          in: path
          type: string
          description: UserName of UAC
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
      responses:
       200:
        description: New Mapping happens
        
  
          
  /{version}/SipUser/Extension:
  
    post:
      
      parameters:
        - name: AddExtention 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Extention'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Updation succeeded
        
  /{version}/SipUser/Extension/{extension}/Status/{st}:
  
    post:
      
      parameters:
      
        - name: extension
          in: path
          type: string
          description: extension 
          
        - name: st
          in: path
          description: Status
          type: boolean
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Extension status updated
        
  
        
  /{version}/SipUser/Extension/{extension}/AssignToSipUser/{id}:
  
    post:
      
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - name: extension
          in: path
          type: string
          description: Extension
          required: true
        
        - name: id
          in: path
          type: integer
          description: UAC ID
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: map extension with user succeeded
        
  
        
  /{version}/SipUser/Group:
  
    post:
      
      parameters:
        - name: Add Sip User group 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/UserGroup'
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
      responses:
       200:
        description: New user group added
        
  /{version}/SipUser/Group/{id}:
  
    post:
      
      parameters:
        - name: Update Sip User group 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/UserGroup'
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
        - name: id
          in: path
          type: integer
          description: Version checking
          required: true
      responses:
       200:
        description: Update sip user group succeeded
        
  /{version}/SipUser/Extension/{extension}/AssignToGroup/{grpid}:
  
    post:
      
      parameters:
             
        - name: extension
          in: path
          type: string
          description: Extension
          required: true
        
        - name: GrpId
          in: path
          type: integer
          description: Group Id
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
      responses:
       200:
        description: Map extension with group succeeded      
  
  /{version}/SipUser/User/ByUUID/{uuid}:
   
   get:
      parameters:
        - name: uuid
          in: path
          type: string
          description: UUID of the Developer
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
          
      responses:
        200:
          description: Sends the Availability
  
    
  /{version}/SipUser/Context/ByCompany/{companyid}:
   
   get:
      parameters:
        - name: companyid
          in: path
          type: integer
          description: Company ID
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
          
      responses:
        200:
          description: All contexts of the company returns
          
  /{version}/SipUser/Group/{groupid}:
   
   get:
      parameters:
        - name: groupid
          in: path
          type: integer
          description: Name of Group
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Group details found
          
  /{version}/SipUser/Group/User/{sipid}:
   
   get:
      parameters:
        - name: sipid
          in: path
          type: integer
          description: ID of SipEndpoint
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Endpoint's group details found
          
          
  /{version}/SipUser/Groups/Company/{companyid}:
   
   get:
      parameters:
        - name: companyid
          in: path
          type: integer
          description: ID of Company
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All groups of company  
  
  /{version}/SipUser/Group/{groupid}/Users:
   
   get:
      parameters:
        - name: groupid
          in: path
          type: integer
          description: ID of Group
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All users of group
          
  /{version}/SipUser/Users/OfCompany/{compid}:
   
   get:
      parameters:
        - name: compid
          in: path
          type: integer
          description: ID of Company
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All users of company        
          
  /{version}/SipUser/Extension/{extension}/Users:
   
   get:
      parameters:
        - name: extension
          in: path
          type: string
          description: ID of Extension
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All users of Extension     
    
  /{version}/SipUser/Extensions/OfCompany/{companyid}:
   
   get:
      parameters:
        - name: companyid
          in: path
          type: integer
          description: ID of Company
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All Extensions of Extension   
          
  /{version}/SipUser/Extension/{extention}:
   
   get:
      parameters:
        - name: extention
          in: path
          type: string
          description: Extension
          required: true
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: All Details of Extension 

          
definitions:

     
  Context:
    properties:
     
     Context:
      type: string
     Description:
      type: string
     ContextCat:
      type: string
     AddUser:
      type: string
     UpdateUser:
      type: string
      
  UAC:
    properties:
     
     SipUsername:
      type: string
     Password:
      type: string
     Enabled:
      type: boolean
     ExtraData:
      type: string
     EmailAddress:
      type: string
     GuRefId:
      type: string
     AddUser:
      type: string
     UpdateUser:
      type: string
     Context:
      type: string
     CloudEndUserId:
      type: integer

      
  UpdtUAC:
    properties:
     
     Password: 
      type: string
     ExtraData:
      type: string
     GuRefId:
      type: string
      
  Extention:
    properties:
     
     Extension:
      type: string
     ExtensionName: 
      type: string
     ExtraData:
      type: string
     AddUser:
      type: string
     UpdateUser:
      type: string
     Enabled:
      type: boolean
     ExtRefId:
      type: string
      
  UserGroup:
    properties:
     
     GroupName:
      type: string
     Domain: 
      type: string
     ExtraData:
      type: string
      
  
     
     
      
  MapExUAC:
    properties:
    
     SipExtension:
      type: string
     CompanyId:
      type: string
   
     
  
      
  
  

  
    
     
 
 
