---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
    host: 127.0.0.1:8011
schemes:
  - http

basePath: /DVP/API
paths:
  /{version}/APPRegistry/AppDeveloperManagement/Developer:
    
    post:
      
      parameters:
        - name: Developer Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Developer'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
      responses:
       200:
        description: New Record Added
        
  /{version}/APPRegistry/VoiceAppManagement/VoiceApp:
  
    post:
      
      parameters:
        - name: Voice App Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/VoiceApp'
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
      responses:
       200:
        description: New Voice app Record Added
        
  /{version}/APPRegistry/VoiceAppManagement/Application/{app}/MapWithDeveloper/{Dev}:
  
    post:
      
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: app
          in: path
          type: string
          description: ApplicationId
          required: true
          
        - name: Dev
          in: path
          type: string
          description: Version checking
          required: true
         
      responses:
       200:
        description: New Mapping happens
        
  /{version}/APPRegistry/VoiceAppManagement/VoiceApp/{id}:
  
    delete:
      
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        - name: id
          in: path
          type: string
          description: Voice App Id
          required: true
          
      responses:
       200:
        description: New Mapping happens
        
  /dvp/:version/APPRegistry/VoiceAppManagement/ChangeVoiceAppAvailability:
  
    post:
      
      parameters:
        - name: Availability updation 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/AppAvailability'
      responses:
       200:
        description: Updation succeeded
        
  /dvp/:version/APPRegistry/VoiceAppManagement/VoiceAppUrlModification:
  
    post:
      
      parameters:
        - name: VoiceApp URL modifocation 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/ModifyUrl'
      responses:
       200:
        description: Url updation succeeded
  
  /dvp/:version/APPRegistry/VoiceAppManagement/URLtest:
  
    post:
      
      parameters:
        - name: Check URL 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/ChkUrl'
      responses:
       200:
        description: Url updation succeeded
        
  /dvp/:version/APPRegistry/VoiceAppManagement/FindAllVoiceAppRecords/{DevID}:
   
   get:
      parameters:
        - name: DevID
          in: path
          type: integer
          description: ID of the Developer
          required: true
      responses:
        200:
          description: Sends the Availability
          
  /dvp/:version/APPRegistry/VoiceAppManagement/FindVoiceAppRecordForID/{VID}/{DevID}:
   
   get:
      parameters:
        - name: DevID
          in: path
          type: integer
          description: ID of the Developer
          required: true
        - name: VID
          in: path
          type: integer
          description: ID of the VoiceApp
          required: true
      responses:
        200:
          description: Sends the Availability
        
        
  
          
definitions:
  Developer:
    properties:
     Username:
      type: string
     Password:
      type: string
     Email:
      type: string
     Phone:
      type: string
     RefId:
      type: string
     Availability:
      type: boolean
      
  VoiceApp:
    properties:
     AppName:
      type: string
     Description:
      type: string
     Url:
      type: string
     Availability:
      type: boolean
      
      

  
  AppAvailability:
    properties:
     Availability:
      type: boolean
      
  ModifyUrl:
    properties:
     VID:
      type: integer
     DevID:
      type: integer
     Url:
      type: string
      
  ChkUrl:
    properties:
     VID:
      type: integer
     DevID:
      type: integer
     Url:
      type: string
     
     
    
     
 
 