---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
    
schemes:
  - http
host : appregistry.104.131.17.220.xip.io
basePath: /DVP/API
paths:
  /{version}/APPRegistry/Developer:
    
    post:
      
      parameters:
        - name: Developer Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Developer'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Record Added
        
  /{version}/APPRegistry/Application:
  
    post:
      
      parameters:
        - name: Voice App Record
          in: body
          description: Record
          schema:
           $ref: '#/definitions/VoiceApp'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Voice app Record Added
        
  /{version}/APPRegistry/Application/{AppID}/AssignToDeveloper/{DevID}:
  
    post:
      
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: AppID
          in: path
          type: string
          description: ApplicationId
          required: true
          
        - name: DevID
          in: path
          type: integer
          description: Version checking
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
         
      responses:
       200:
        description: New Mapping happens
   
  /{version}/APPRegistry/Application/{CAppID}/SetAsMasterApp/{MAppID}:
  
    post:
      
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: MAppID
          in: path
          type: string
          description: Master ApplicationId
          required: true
          
        - name: CAppID
          in: path
          type: integer
          description: Child ApplicationId
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
         
      responses:
       200:
        description: New Mapping happens 
  
  
       
  /{version}/APPRegistry/Application/{id}:
  
    delete:
      
      parameters:
        
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: id
          in: path
          type: integer
          description: Voice App Id
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: New Mapping happens
        
  /{version}/APPRegistry/Application/{id}/Activate/{status}:
  
    post:
      
      parameters:
      
      
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: id
          in: path
          type: integer
          description: Voice App Id
          required: true
        
        - name: status
          in: path
          type: string
          description: Status
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Updation succeeded
        
  /{version}/APPRegistry/Application/{AppID}/URL:
  
    post:
      
      parameters:
        - name: VoiceApp URL modifocation 
          in: body
          description: Record
          schema:
           $ref: '#/definitions/ModifyUrl'
           
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: AppID
          in: path
          type: integer
          description: Voice App Id
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Url updation succeeded
  
  /{version}/APPRegistry/Application/{AppID}/Test:
  
    post:
      
      parameters:
       
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - name: AppID
          in: path
          type: integer
          description: Voice App Id
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Url updation succeeded
        
  /{version}/APPRegistry/Applications/{DevID}:
   
   get:
      parameters:
        - name: DevID
          in: path
          type: integer
          description: ID of the Developer
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
          
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
          
      responses:
        200:
          description: Sends the Availability
          
  /{version}/APPRegistry/ApplicationDetails/{AppID}:
   
   get:
      parameters:
        
        - name: AppID
          in: path
          type: integer
          description: ID of the VoiceApp
          required: true
          
        - name: version
          in: path
          type: string
          description: Version checking
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
        200:
          description: Sends the Availability
        
        
  
          
definitions:
  Developer:
    properties:
     Username:
      type: string
     Password:
      type: string
     Email:
      type: string
     Phone:
      type: string
     RefId:
      type: string
     Availability:
      type: boolean
      
  VoiceApp:
    properties:
     AppName:
      type: string
     Description:
      type: string
     Url:
      type: string
     Availability:
      type: boolean
     IsDeveloper:
      type: boolean
     Protocol:
      type: string
      
   
  ModifyUrl:
    properties:
    
     DevID:
      type: integer
     Url:
      type: string
      
  
     
     
    
     
 
 