---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
schemes:
  - http

host: ruleservice.104.131.17.220.xip.io
basePath: /DVP/API
paths:

  /{hostVersion}/CallRuleApi/CallRules:
   
   get:
      description: Api method to retrieve all call rules
      parameters:
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Call rules returned 
          
  /{hostVersion}/CallRuleApi/CallRule/{id}:
   
   get:
      description: API method to retrieve a call rule with given id
      parameters:
      
        - name: id
          in: path
          type: integer
          description: Call rule id
          required: true
        
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Call rule returned
          
  /{hostVersion}/CallRuleApi/CallRule/Outbound/ANI/{ani}/DNIS/{dnis}:
   
   get:
      description: API method to pick correct outbound rule, do neccessary translations and provide complete set of data required to put an outbound call
      parameters:
      
        - name: ani
          in: path
          type: string
          description: From number to match
          required: true
          
        - name: dnis
          in: path
          type: string
          description: To number to match
          required: true  
        
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Complete outbound rule returned


  /{hostVersion}/CallRuleApi/CallRule/{id}/SetTrunkNumber/{trNum}:
    
    post:
      
      description: Method to set an outbound trunk number to an outbound rule
      parameters:
        - name: id
          in: path
          type: integer
          description: Call rule id
          
        - name: trNum
          in: path
          type: string
          description: Outbound trunk number
          
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Trunk number has been set
          
  /{hostVersion}/CallRuleApi/CallRule/{id}/SetRegEx:
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: Call rule id
          
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
        - name: callruleRegEx Details
          in: body
          description: Call rule regular expressions
          schema:
           $ref: '#/definitions/CallRuleRegEx'
          
        
          
      responses:
       200:
        description: call rule regex succeeded
        
        
  /{hostVersion}/CallRuleApi/CallRule/{id}/SetAvailability/{enabled} :
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: Call rule id
        
        - name: enabled
          in: path
          type: boolean
          description: Call rule availability
          
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: call availability has been set
        
  /{hostVersion}/CallRuleApi/CallRule/{id}/SetPriority/{priority} :
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: Call rule id
          
        - name: priority
          in: path
          type: integer
          description: Priority
          
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
          
      responses:
       200:
        description: call priority has been set
        
  /{hostVersion}/CallRuleApi/CallRule/{id}/SetSchedule/{scheduleId} :
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: Call rule id
          
        - name: scheduleId
          in: path
          type: integer
          description: Schedule id
        
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
       200:
        description: Call RuleSchedule has been set   
        
  /{hostVersion}/CallRuleApi/CallRule/{id}/SetTranslation/{transId} :
    
    post:
    
      parameters:
        - name: id
          in: path
          type: integer
          description: Call rule id
          
        - name: transId
          in: path
          type: integer
          description: Translation id
        
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Call rule translation has been set 
        
  /{hostVersion}/CallRuleApi/CallRule/Outbound :
    
    post:
    
      parameters:
        - name: New OutBound Rule
          in: body
          description: Record
          schema:
           $ref: '#/definitions/CallRuleOtBound'
        
        - name: hostVersion
          in: path
          type: string
          description: API version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: OutBound rule has been set 
  
  /{hostVersion}/CallRuleApi/CallRule/Inbound :
    
    post:
    
      parameters:
        - name: New Inbound rule
          in: body
          description: New Inbound rule
          schema:
           $ref: '#/definitions/CallRuleOtBound'
        
        - name: hostVersion
          in: path
          type: string
          description: API Version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Inbound rule has been set 
        
  /DVP/API/:version/CallRuleApi/CallRule/{ruleId}/SetApplication/{appId} :
    
    post:
    
      parameters:
        - name: appId
          in: path
          type: integer
          description: appId
        - name: ruleId
          in: path
          type: integer
          description: ruleId
        
          
      responses:
       200:
        description: App added to rule
        
        
  /{hostVersion}/CallRuleApi/CallRule/{id} :
    
    delete:
      
    
      parameters:
        - name: id
          in: path
          type: integer
          description: id
          
        - name: hostVersion
          in: path
          type: string
          description: API Version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
        
          
      responses:
       200:
        description: Call rule has been deleted         


  /{hostVersion}/CallRuleApi/Translations:
   
   get:
      parameters:
        - name: hostVersion
          in: path
          type: string
          description: API Version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Translations for Company returned 
  
  /{hostVersion}/CallRuleApi/Translation/{id}:
   
   get:
      parameters:
        - name: id
          in: path
          type: integer
          description: ID of the Company
          required: true
        
        - name: hostVersion
          in: path
          type: string
          description: API Version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
        
      responses:
        200:
          description: Get translation success 
  
  /{hostVersion}/CallRuleApi/Translation :
    
    post:
    
      parameters:
        - name: Translation Details
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Translation'
        
        - name: hostVersion
          in: path
          type: string
          description: API Version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
      responses:
       200:
        description: Translation added 
  
  /{hostVersion}/CallRuleApi/Translation/{id} :
    
    post:
    
      parameters:
        - name: Translation Details
          in: body
          description: Record
          schema:
           $ref: '#/definitions/Translation'
        
        - name: hostVersion
          in: path
          type: string
          description: API Version
          required: true
        
        - in: header
          name: authorization
          description: ""
          required: true
          type: string
          
        - in: path
          name: id
          description: ""
          required: true
          type: integer
          
      responses:
       200:
        description: Translation updated
        
     
definitions:

  CallRuleOtBound:
    properties:
     
     Direction:
      {
        description: Call rule direction,
        type: string,
        enum: ["INBOUND", "OUTBOUND"]
      }
     Enable:
      type: boolean
     RegExPattern:
      {
        description: Regular expression type for DNIS,
        type: string,
        enum: ["STARTWITH", "EXACTMATCH", "ANY", "CUSTOM"]
      }
     ANIRegExPattern:
      {
        description: Regular expression type for ANI,
        type: string,
        enum: ["STARTWITH", "EXACTMATCH", "ANY", "CUSTOM"]
      }
     Context:
      type: string
     DNIS:
      type: string
     ANI:
      type: string
     Priority:
      type: integer
     TrunkId:
      type: integer
     TrunkNumber:
      type: string
     ExtraData:
      type: string
     
  
  Translation:
    properties:
     
     TransName:
      type: string
     ObjType: 
      type: string
     ObjClass:
      type: string
     ObjCategory:
      type: string
     TenantId:
      type: integer
     CompanyId:
      type: integer
     TransDescription :
      type: string
     Enable:
      type: boolean
     LAdd:
      type: string
     LRemove:
      type: string
     RAdd:
      type: string
     RRemove:
      type: string
     Replace:
      type: integer
  

      
  CallRuleRegEx:
    properties:
     
     DNISRegExMethod:
      {
        description: Regular expression type for DNIS,
        type: string,
        enum: ["STARTWITH", "EXACTMATCH", "ANY", "CUSTOM"]
      }
     ANIRegExMethod:
      {
        description: Regular expression type for ANI,
        type: string,
        enum: ["STARTWITH", "EXACTMATCH", "ANY", "CUSTOM"]
      }
     DNIS:
      description: To number
      type: string
     ANI:
      description: From number
      type: string
  
  
    
     
 
 
